channels:
- conda-forge
- defaults
dependencies:
- cartopy=0.16.0
- ipykernel=4.8.2
- matplotlib=2.2.2
- numpy=1.14.2
- pandas=0.22.0
- python=3.6.5=1
- scikit-learn=0.19.1
- scipy=1.0.1
- seaborn=0.8.1
- statsmodels=0.8.0
